---
# deploy-honeypots.yml
# Playbook Ansible para desplegar el cluster de honeypots benchmark 2026
# Autor: Dr. Giovanni Carlos Lorusso Montiel
# Fecha: Diciembre 2025
# Requisitos: Instalar colección community.docker (ansible-galaxy collection install community.docker)

- name: Preparación base en todas las VMs
  hosts: all
  become: yes
  tasks:
    - name: Actualizar sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar Docker y Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose-plugin  # Para Compose v2
        state: present

- name: Desplegar honeypots individuales
  hosts: honeypots
  become: yes
  tasks:
    - name: Crear directorio de trabajo
      file:
        path: /opt/honeypot
        state: directory
        mode: '0755'

    - name: Copiar carpeta específica del honeypot (basado en hostname)
      copy:
        src: "honeypots/{{ inventory_hostname }}/"
        dest: /opt/honeypot/
        mode: preserve

    - name: Desplegar contenedor con Docker Compose
      community.docker.docker_compose:
        project_src: /opt/honeypot/
        state: present
        restarted: yes
      register: compose_output

    - name: Mostrar resultado del despliegue
      debug:
        var: compose_output

- name: Configuración opcional en VM central (monitor + tcpreplay)
  hosts: central-monitor
  become: yes
  tasks:
    - name: Instalar herramientas de réplica y monitoreo
      apt:
        name:
          - tcpdump
          - tcpreplay
          - prometheus-node-exporter
        state: present
